"""Add email, address, DOB, gender, allergies, medications, provider to MedicalRecord

Revision ID: a9e11bb76172
Revises: 11fd0fbe1761
Create Date: 2025-05-08 20:31:24.427399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e11bb76172'
down_revision = '11fd0fbe1761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('allergies', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('provider_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_column('provider_name')
        batch_op.drop_column('medications')
        batch_op.drop_column('allergies')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('address')
        batch_op.drop_column('patient_email')

    # ### end Alembic commands ###
